# Generated by Django 4.2.28 on 2026-03-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_nutrients_and_foodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='condition_rules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
