# Generated by Django 4.2.28 on 2026-03-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_health_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stats_tracked_nutrients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
