# Generated by Django 4.2.28 on 2026-03-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_stats_tracked_nutrients'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_avatar',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
