# Generated by Django 4.2.28 on 2026-02-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=255)),
                ('image_url', models.URLField(blank=True, default='')),
                ('nutriscore_grade', models.CharField(blank=True, default='', max_length=1)),
                ('nova_group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('energy_kcal', models.FloatField(blank=True, null=True)),
                ('fat', models.FloatField(blank=True, null=True)),
                ('saturated_fat', models.FloatField(blank=True, null=True)),
                ('sugars', models.FloatField(blank=True, null=True)),
                ('salt', models.FloatField(blank=True, null=True)),
                ('proteins', models.FloatField(blank=True, null=True)),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('ingredients_text', models.TextField(blank=True, default='')),
                ('categories', models.CharField(blank=True, default='', max_length=512)),
                ('source', models.CharField(default='openfoodfacts', help_text='Origin API the data was fetched from', max_length=32)),
                ('raw_json', models.JSONField(blank=True, help_text='Full original API response for future re-processing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
